import type { DrawingDocument, ElectricalSymbol, Phase } from '../drawing/model';
import type { LabelScheme } from '../../app/labeling/types';
import { inferBp109MetaForDocument, isBp109AnchorSymbol, labelFromBp109Meta } from './inferBp109V2';
import { parseBp109Label } from './parseBp109';
import { voltageClassFromKv } from '../../app/labeling/bp109';
import {
  ansiFunctionForKind,
  computeAnsiIecLabel,
  defaultAnsiIecMeta
} from '../../app/labeling/bp109';

const TYPE_PREFIX: Record<ElectricalSymbol['type'], string> = {
  source: 'IN',
  load: 'LD',
  'grid-connection': 'GC',
  'busbar-coupler': 'BC',
  'circuit-breaker': 'CB',
  disconnector: 'DS',
  'earth-switch': 'ES',
  transformer: 'T',
  vt: 'VT',
  ct: 'CT',
  'cable-sealing-end': 'CSE',
  'line-end': 'LE'
};

const phaseMarker = (phases: Phase[]) => (phases.length < 3 || !['A', 'B', 'C'].every((p) => phases.includes(p as Phase)) ? '*' : '');

function symbolKind(type: ElectricalSymbol['type']): string {
  if (type === 'circuit-breaker') return 'cb';
  if (type === 'disconnector') return 'ds';
  if (type === 'earth-switch') return 'es';
  if (type === 'transformer') return 'tx';
  if (type === 'vt') return 'vt';
  if (type === 'ct') return 'ct';
  if (type === 'source') return 'source';
  if (type === 'load') return 'load';
  if (type === 'grid-connection') return 'source';
  return type;
}

function substationVoltageKv(doc: DrawingDocument): number {
  return doc.voltageLevels[0] ?? doc.objects.symbols.find((symbol) => symbol.voltageLevelKv)?.voltageLevelKv ?? 400;
}

export function resolveLabelScheme(doc: DrawingDocument): LabelScheme {
  return doc.uiState.labelScheme ?? 'DEFAULT';
}

export function generateLabels(doc: DrawingDocument, scheme: LabelScheme = resolveLabelScheme(doc)): DrawingDocument {
  if (scheme === 'NG_BP109') return generateBp109Labels(doc, scheme);
  return generateDefaultLabels(doc, scheme);
}

function generateBp109Labels(doc: DrawingDocument, scheme: LabelScheme): DrawingDocument {
  const inferred = inferBp109MetaForDocument(doc);
  const used = new Set<string>();
  const voltageClass = voltageClassFromKv(substationVoltageKv(doc));

  doc.objects.symbols.forEach((symbol) => {
    if (isBp109AnchorSymbol(symbol, doc) && symbol.label?.text) used.add(symbol.label.text);
  });

  const symbols = doc.objects.symbols.map((symbol) => {
    if (isBp109AnchorSymbol(symbol, doc) && symbol.label?.manualOverride) {
      const parsed = parseBp109Label(symbol.label.text, voltageClass);
      return {
        ...symbol,
        engineering: {
          ...symbol.engineering,
          bp109: {
            ...symbol.engineering?.bp109,
            circuitNumber: parsed?.circuitNumber ?? symbol.engineering?.bp109?.circuitNumber,
            circuitType: parsed?.circuitType ?? symbol.engineering?.bp109?.circuitType,
            purposeDigit: parsed?.purposeDigit ?? symbol.engineering?.bp109?.purposeDigit
          }
        }
      };
    }

    const meta = inferred[symbol.id];
    if (!meta) return symbol;

    let candidate = `${labelFromBp109Meta(meta)}${phaseMarker(symbol.phaseApplicability)}`;
    let suffix = 1;
    while (used.has(candidate)) {
      suffix += 1;
      candidate = `${labelFromBp109Meta(meta)}-${suffix}${phaseMarker(symbol.phaseApplicability)}`;
    }
    used.add(candidate);

    return {
      ...symbol,
      label: {
        text: candidate,
        autoGenerated: true,
        manualOverride: false,
        marker: candidate.endsWith('*') ? '* phase-specific device' : undefined
      },
      engineering: {
        ...symbol.engineering,
        bp109: {
          circuitType: meta.circuitType,
          circuitNumber: meta.circuitNumber,
          purposeDigit: meta.purposeDigit,
          prefix: meta.prefix,
          suffixLetter: meta.suffixLetter
        }
      }
    };
  });

  return {
    ...doc,
    uiState: { ...doc.uiState, labelScheme: scheme },
    objects: { ...doc.objects, symbols }
  };
}

function generateDefaultLabels(doc: DrawingDocument, scheme: LabelScheme): DrawingDocument {
  const used = new Set<string>();
  const sorted = [...doc.objects.symbols].sort((a, b) => a.position.x - b.position.x || a.position.y - b.position.y);
  const bayBySymbolId = new Map<string, number>();
  sorted.forEach((symbol, index) => {
    if (['circuit-breaker', 'disconnector', 'earth-switch', 'transformer', 'load', 'source', 'grid-connection'].includes(symbol.type)) {
      bayBySymbolId.set(symbol.id, index + 1);
    }
  });

  const symbols = doc.objects.symbols.map((symbol) => {
    if (symbol.label?.manualOverride) {
      used.add(symbol.label.text);
      return symbol;
    }

    const base = makeLabelForScheme(symbol, scheme, bayBySymbolId.get(symbol.id) ?? 1);
    let candidate = `${base}${phaseMarker(symbol.phaseApplicability)}`;
    let suffix = 1;
    while (used.has(candidate)) {
      suffix += 1;
      candidate = `${base}-${suffix}${phaseMarker(symbol.phaseApplicability)}`;
    }

    used.add(candidate);
    return {
      ...symbol,
      label: {
        text: candidate,
        autoGenerated: true,
        manualOverride: false,
        marker: candidate.endsWith('*') ? '* phase-specific device' : undefined
      }
    };
  });

  return {
    ...doc,
    uiState: { ...doc.uiState, labelScheme: scheme },
    objects: { ...doc.objects, symbols }
  };
}

function makeLabelForScheme(symbol: ElectricalSymbol, scheme: LabelScheme, bayNumber: number): string {
  const kind = symbolKind(symbol.type);
  if (scheme === 'ANSI_IEC') {
    const meta = {
      ...defaultAnsiIecMeta(kind),
      bayNumber,
      functionCode: ansiFunctionForKind(kind),
      enabled: kind === 'cb' || kind === 'ds' || kind === 'es' || kind === 'ct' || kind === 'vt'
    };
    if (!meta.enabled) return makeDefaultLabel(symbol, bayNumber);
    return computeAnsiIecLabel(meta);
  }
  return makeDefaultLabel(symbol, bayNumber);
}

function makeDefaultLabel(symbol: ElectricalSymbol, index: number): string {
  const voltage = symbol.voltageLevelKv ? `${symbol.voltageLevelKv}kV ` : '';
  if (symbol.type === 'transformer') return `${voltage}Transformer T${index}`;
  if (symbol.type === 'source') return `${voltage}Incomer ${index}`;
  if (symbol.type === 'grid-connection') return `${voltage}Grid ${index}`;
  if (symbol.type === 'load') return `${voltage}Feeder ${index}`;
  return `${voltage}${TYPE_PREFIX[symbol.type]}${String(index).padStart(3, '0')}`;
}
