import { describe, expect, it } from 'vitest';
import type { DrawingDocument } from '../drawing/model';
import { MIMIC_DESIGNER_V2_SCHEMA_VERSION, migrateDrawingDocument, serializeDrawingDocument } from '../schema/documentSchema';

describe('Mimic Designer V2 document schema migration', () => {
  it('loads older minimal documents with safe defaults', () => {
    const migrated = migrateDrawingDocument({
      id: 'old-doc',
      version: 2,
      name: 'Old',
      activeView: 'single-line',
      objects: {
        symbols: [
          {
            id: 'ct-1',
            type: 'ct',
            position: { x: 100, y: 100 },
            rotation: 0,
            terminals: [{ id: 't-0', name: 'in', offset: { x: -20, y: 0 }, phaseApplicability: [] }],
            phaseApplicability: []
          } as any
        ]
      }
    });

    expect(migrated?.schemaVersion).toBe(MIMIC_DESIGNER_V2_SCHEMA_VERSION);
    expect(migrated?.uiState.gridSize).toBe(20);
    expect(migrated?.objects.symbols[0].phaseApplicability).toEqual(['A', 'B', 'C']);
    expect(migrated?.objects.symbols[0].operation?.tripped).toBe(false);
    expect(migrated?.objects.symbols[0].engineering?.ctPolarity).toBe('P1-left');
    expect(migrated?.hotJoints).toEqual([]);
    expect(migrated?.protection).toEqual([]);
    expect(migrated?.simulationState.running).toBe(false);
  });

  it('preserves engineering, operation, voltage, labels, and phases when serializing', () => {
    const doc = migrateDrawingDocument({
      id: 'doc',
      version: 2,
      schemaVersion: 1,
      name: 'Persist me',
      activeView: 'three-phase',
      objects: {
        symbols: [
          {
            id: 'tx-1',
            type: 'transformer',
            position: { x: 200, y: 120 },
            rotation: 0,
            voltageLevelKv: 132,
            phaseApplicability: ['A', 'B', 'C'],
            label: { text: '132kV Transformer T1', autoGenerated: false, manualOverride: true },
            engineering: { transformerPolarity: 'hv-right', hasTertiary: true, tertiaryVoltageKv: 33 },
            operation: { tripped: true },
            terminals: [
              { id: 'hv', name: 'hv', offset: { x: -40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] },
              { id: 'lv', name: 'lv', offset: { x: 40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] },
              { id: 'ter', name: 'tertiary', offset: { x: 0, y: 34 }, phaseApplicability: ['B'] }
            ]
          } as any
        ]
      },
      faults: [{ id: 'fault-1', targetObjectId: 'tx-1', type: 'A-E', phases: ['A'], persistent: true, active: true, createdAt: '2026-01-01T00:00:00.000Z' }],
      hotJoints: [{ id: 'hj-1', targetObjectId: 'tx-1', phase: 'B', addedResistanceOhms: 0.2, thermalMassFactor: 2, ambientTemperatureC: 18, warningTemperatureC: 60, dangerTemperatureC: 90, intermittent: false, active: true }],
      protection: [{ id: 'ef-1', type: 'earth-fault', enabled: true, watchedObjectId: 'tx-1', phases: ['A'], pickupCurrentA: 100, timeDelayMs: 250, tripTargetBreakerIds: ['cb-1'], state: 'idle' }],
      simulationState: { running: true, speed: 2, overlay: 'thermal' }
    }) as DrawingDocument;

    const saved = serializeDrawingDocument(doc);
    const tx = saved.objects.symbols[0];
    expect(saved.schemaVersion).toBe(MIMIC_DESIGNER_V2_SCHEMA_VERSION);
    expect(tx.voltageLevelKv).toBe(132);
    expect(tx.label?.text).toBe('132kV Transformer T1');
    expect(tx.engineering?.transformerPolarity).toBe('hv-right');
    expect(tx.engineering?.tertiaryVoltageKv).toBe(33);
    expect(tx.operation?.tripped).toBe(true);
    expect(tx.terminals.find((terminal) => terminal.name === 'tertiary')?.phaseApplicability).toEqual(['B']);
    expect(saved.faults[0].targetPhase).toBe('A');
    expect(saved.hotJoints[0].phase).toBe('B');
    expect(saved.protection[0].tripTargetBreakerIds).toEqual(['cb-1']);
    expect(saved.simulationState.overlay).toBe('thermal');
  });
});
