import { describe, expect, it } from 'vitest';
import { addStep, createSequence } from '../animation/sequence';
import type { ElectricalSymbol } from '../drawing/model';
import { migrateDrawingDocument } from '../schema/documentSchema';
import { buildAnimatedSequenceExportSvg, buildDrawingExportSvg } from '../rendering/drawingExport';

const symbol = (patch: Partial<ElectricalSymbol> & Pick<ElectricalSymbol, 'id' | 'type' | 'position' | 'terminals'>): ElectricalSymbol => ({
  rotation: 90,
  phaseApplicability: ['A', 'B', 'C'],
  simulation: {},
  operation: { switchState: 'open', tripped: false },
  label: { text: 'X135', autoGenerated: true, manualOverride: false },
  ...patch
});

const doc = migrateDrawingDocument({
  id: 'doc-1',
  version: 2,
  name: 'Export test',
  activeView: 'single-line',
  objects: {
    symbols: [symbol({
      id: 'cb-1',
      type: 'circuit-breaker',
      position: { x: 200, y: 200 },
      terminals: [
        { id: 'in', name: 'in', offset: { x: -40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] },
        { id: 'out', name: 'out', offset: { x: 40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] }
      ]
    })],
    conductors: [],
    busbars: [],
    labels: [],
    annotations: []
  }
})!;

describe('drawingExport', () => {
  it('keeps equipment labels horizontal for vertical components', () => {
    const svg = buildDrawingExportSvg(doc, { theme: 'light', labelMode: 'all' });
    expect(svg).toContain('rotate(-90)');
    expect(svg).toContain('Segoe UI');
    expect(svg).toContain('X135');
  });

  it('builds animated sequence SVG with captions and energisation animation', () => {
    const sequence = addStep(createSequence('Test sequence'), { name: 'Close breaker', actionType: 'wait' });
    const svg = buildAnimatedSequenceExportSvg(doc, sequence, { theme: 'light', labelMode: 'all' });
    expect(svg).toContain('Animated Sequence');
    expect(svg).toContain('Close breaker');
    expect(svg).toContain('<animate attributeName="opacity"');
  });
});
