import { describe, expect, it } from 'vitest';
import { addStep, createSequence } from '../animation/sequence';
import type { ElectricalSymbol } from '../drawing/model';
import { migrateDrawingDocument } from '../schema/documentSchema';
import { buildAnimatedSequenceExportSvg, buildDrawingExportSvg } from '../rendering/drawingExport';
import { SEQUENCE_INTRO_SECONDS } from '../animation/sequenceSimulation';

const symbol = (patch: Partial<ElectricalSymbol> & Pick<ElectricalSymbol, 'id' | 'type' | 'position' | 'terminals'>): ElectricalSymbol => ({
  rotation: 90,
  phaseApplicability: ['A', 'B', 'C'],
  simulation: {},
  operation: { switchState: 'open', tripped: false },
  label: { text: 'X135', autoGenerated: true, manualOverride: false },
  ...patch
});

const doc = migrateDrawingDocument({
  id: 'doc-1',
  version: 2,
  name: 'Export test',
  activeView: 'single-line',
  objects: {
    symbols: [symbol({
      id: 'cb-1',
      type: 'circuit-breaker',
      position: { x: 200, y: 200 },
      terminals: [
        { id: 'in', name: 'in', offset: { x: -40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] },
        { id: 'out', name: 'out', offset: { x: 40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] }
      ]
    })],
    conductors: [],
    busbars: [],
    labels: [],
    annotations: []
  }
})!;

describe('drawingExport', () => {
  it('keeps equipment labels horizontal for vertical components', () => {
    const svg = buildDrawingExportSvg(doc, { theme: 'light', labelMode: 'all' });
    expect(svg).toContain('rotate(-90)');
    expect(svg).toContain('Segoe UI');
    expect(svg).not.toContain('font-family=""');
    expect(svg).toContain('X135');
  });

  it('renders energised paths as a separate overlay layer', () => {
    const svg = buildDrawingExportSvg(doc, { theme: 'light', labelMode: 'all', showEnergizedPaths: true });
    expect(svg).toContain('id="energized-overlay"');
    expect(svg).toContain('id="drawing-base"');
  });

  it('builds animated sequence SVG with timed frames and event log below drawing', () => {
    const closedDoc = migrateDrawingDocument({
      ...doc,
      objects: {
        ...doc.objects,
        symbols: doc.objects.symbols.map((item) => ({
          ...item,
          operation: { ...item.operation, switchState: 'closed' as const }
        }))
      }
    })!;
    const sequence = addStep(createSequence('Test sequence'), {
      name: 'circuit breaker - X135 - closed',
      actionType: 'close-circuit-breaker',
      targetId: 'cb-1'
    });
    const svg = buildAnimatedSequenceExportSvg(closedDoc, sequence, { theme: 'light', labelMode: 'all' });
    expect(svg).toContain('Animated Sequence');
    expect(svg).toContain('id="sequence-frames"');
    expect(svg).toContain('id="sequence-event-log"');
    expect(svg).toContain(`[${SEQUENCE_INTRO_SECONDS.toFixed(1)}s]`);
    expect(svg).toContain('circuit breaker - X135 - closed');
    expect(svg).toContain('fill="freeze"');
    expect(svg).not.toContain('repeatCount="indefinite"');
    expect(svg).toContain('stroke="#dc2626"');
  });

  it('supports many sequence steps without stacked caption overlap', () => {
    let sequence = createSequence('Long sequence');
    for (let index = 0; index < 16; index += 1) {
      sequence = addStep(sequence, {
        name: `disconnector - X10${index} - closed`,
        actionType: 'wait',
        eventDurationSeconds: 0.5,
        delayAfterSeconds: 0.1
      });
    }
    const svg = buildAnimatedSequenceExportSvg(doc, sequence, { theme: 'light', labelMode: 'none' });
    expect(svg).toContain('steps: 16');
    expect((svg.match(/id="sequence-event-log"/g) ?? []).length).toBe(1);
    expect((svg.match(/\[0\.0s\]/g) ?? []).length).toBe(0);
    expect((svg.match(/\[9\.[0-9]s\]/g) ?? []).length).toBeGreaterThanOrEqual(1);
  });
});
