import { describe, expect, it } from 'vitest';
import { generateLabels } from '../nomenclature/engine';
import { parseBp109Label, parseLineCircuitNumber } from '../nomenclature/parseBp109';
import { busbar, createBaseDocument, symbol } from '../templates/factory';
import { extractTopology } from '../topology/extractTopology';

describe('BP109 nomenclature', () => {
  it('parses 400kV BP109 labels', () => {
    expect(parseBp109Label('X305', '400')).toMatchObject({ circuitNumber: 3, circuitType: 'LINE', purposeDigit: 5 });
    expect(parseBp109Label('X124', '400')).toMatchObject({ circuitNumber: 1, circuitType: 'MAIN_BUS_SEC', purposeDigit: 4 });
  });

  it('parses line feeder names', () => {
    expect(parseLineCircuitNumber('Line 3')).toBe(3);
    expect(parseLineCircuitNumber('3')).toBe(3);
    expect(parseLineCircuitNumber('Feeder 7')).toBe(7);
  });

  it('propagates anchored line names to switchgear in the same bay', () => {
    const doc = createBaseDocument('bp109-test', 'BP109 test', {
      voltageLevels: [400],
      objects: {
        symbols: [
          symbol('line-1', 'grid-connection', 100, 220, 'Line 1', 400, 90, { label: { text: 'Line 1', autoGenerated: false, manualOverride: true } }),
          symbol('line-1-ds', 'disconnector', 100, 300, 'OLD', 400, 90),
          symbol('line-1-cb', 'circuit-breaker', 100, 380, 'OLD CB', 400, 90),
          symbol('line-3', 'grid-connection', 300, 220, 'X305', 400, 90, { label: { text: 'X305', autoGenerated: false, manualOverride: true } }),
          symbol('line-3-ds', 'disconnector', 300, 300, 'OLD', 400, 90)
        ],
        busbars: [
          busbar('drop-1', [{ x: 100, y: 240 }, { x: 100, y: 420 }], 400),
          busbar('drop-3', [{ x: 300, y: 240 }, { x: 300, y: 340 }], 400)
        ],
        conductors: [],
        labels: [],
        annotations: []
      },
      uiState: { gridSize: 20, snapToGrid: true, snapToTerminals: true, snapToIntersections: true, labelScheme: 'NG_BP109' }
    });

    extractTopology(doc);
    const labelled = generateLabels(doc, 'NG_BP109');
    const line1Cb = labelled.objects.symbols.find((item) => item.id === 'line-1-cb');
    const line3Ds = labelled.objects.symbols.find((item) => item.id === 'line-3-ds');
    const line1Endpoint = labelled.objects.symbols.find((item) => item.id === 'line-1');

    expect(line1Endpoint?.label?.text).toBe('Line 1');
    expect(line1Cb?.label?.text).toBe('X105');
    expect(line3Ds?.label?.text).toBe('X303');
  });

  it('labels double-busbar line bays with selector and line-end disconnectors', () => {
    const mainBar = busbar('main-bar', [{ x: 200, y: 220 }, { x: 400, y: 220 }], 400);
    mainBar.engineering = { busbarRole: 'main' };
    const reserveBar = busbar('reserve-bar', [{ x: 200, y: 360 }, { x: 400, y: 360 }], 400);
    reserveBar.engineering = { busbarRole: 'reserve' };

    const doc = createBaseDocument('bp109-double-bus', 'Double bus', {
      voltageLevels: [400],
      objects: {
        symbols: [
          symbol('line-3', 'grid-connection', 300, 180, '3', 400, 90, { label: { text: '3', autoGenerated: false, manualOverride: true } }),
          symbol('line-3-main-ds', 'disconnector', 300, 250, 'OLD', 400, 90),
          symbol('line-3-reserve-ds', 'disconnector', 300, 330, 'OLD', 400, 90),
          symbol('line-3-cb', 'circuit-breaker', 300, 400, 'OLD', 400, 90),
          symbol('line-3-line-ds', 'disconnector', 300, 480, 'OLD', 400, 90)
        ],
        busbars: [
          mainBar,
          reserveBar,
          busbar('bay-drop', [{ x: 300, y: 200 }, { x: 300, y: 520 }], 400)
        ],
        conductors: [],
        labels: [],
        annotations: []
      },
      uiState: { gridSize: 20, snapToGrid: true, snapToTerminals: true, snapToIntersections: true, labelScheme: 'NG_BP109' }
    });

    extractTopology(doc);
    const labelled = generateLabels(doc, 'NG_BP109');
    expect(labelled.objects.symbols.find((item) => item.id === 'line-3-main-ds')?.label?.text).toBe('X304');
    expect(labelled.objects.symbols.find((item) => item.id === 'line-3-reserve-ds')?.label?.text).toBe('X306');
    expect(labelled.objects.symbols.find((item) => item.id === 'line-3-line-ds')?.label?.text).toBe('X303');
    expect(labelled.objects.symbols.find((item) => item.id === 'line-3-cb')?.label?.text).toBe('X305');
  });
});
