import { describe, expect, it } from 'vitest';
import { addStep, createSequence } from '../animation/sequence';
import type { ElectricalSymbol } from '../drawing/model';
import { migrateDrawingDocument } from '../schema/documentSchema';
import {
  applySequenceStep,
  buildInitialDocForSequence,
  buildSequenceSnapshots,
  rewindSequenceStep,
  SEQUENCE_INTRO_SECONDS
} from '../animation/sequenceSimulation';

const symbol = (patch: Partial<ElectricalSymbol> & Pick<ElectricalSymbol, 'id' | 'type' | 'position' | 'terminals'>): ElectricalSymbol => ({
  rotation: 0,
  phaseApplicability: ['A', 'B', 'C'],
  simulation: {},
  operation: { switchState: 'open', tripped: false },
  label: { text: patch.id, autoGenerated: true, manualOverride: false },
  ...patch
});

describe('sequenceSimulation', () => {
  it('rewinds imported close steps so replay starts from open', () => {
    const finalDoc = migrateDrawingDocument({
      id: 'doc-1',
      version: 2,
      name: 'Replay test',
      activeView: 'single-line',
      objects: {
        symbols: [symbol({
          id: 'cb-1',
          type: 'circuit-breaker',
          position: { x: 100, y: 100 },
          terminals: [
            { id: 'in', name: 'in', offset: { x: -40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] },
            { id: 'out', name: 'out', offset: { x: 40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] }
          ],
          operation: { switchState: 'closed', tripped: false }
        })],
        conductors: [],
        busbars: [],
        labels: [],
        annotations: []
      }
    })!;

    const step = {
      name: 'circuit breaker - cb-1 - closed',
      actionType: 'close-circuit-breaker' as const,
      targetId: 'cb-1'
    };
    const sequence = addStep(createSequence('Replay'), step);
    const initialDoc = buildInitialDocForSequence(finalDoc, sequence);
    const cb = initialDoc.objects.symbols.find((item) => item.id === 'cb-1');

    expect(cb?.operation?.switchState).toBe('open');

    const replayed = applySequenceStep(initialDoc, sequence.steps[0]);
    expect(replayed.objects.symbols.find((item) => item.id === 'cb-1')?.operation?.switchState).toBe('closed');
    expect(rewindSequenceStep(finalDoc, sequence.steps[0]).objects.symbols.find((item) => item.id === 'cb-1')?.operation?.switchState).toBe('open');
  });

  it('builds distinct snapshots for each step', () => {
    let sequence = createSequence('Two-step');
    sequence = addStep(sequence, { name: 'Close A', actionType: 'close-circuit-breaker', targetId: 'cb-a' });
    sequence = addStep(sequence, { name: 'Close B', actionType: 'close-circuit-breaker', targetId: 'cb-b' });

    const finalDoc = migrateDrawingDocument({
      id: 'doc-2',
      version: 2,
      name: 'Two-step',
      activeView: 'single-line',
      objects: {
        symbols: [
          symbol({
            id: 'cb-a',
            type: 'circuit-breaker',
            position: { x: 80, y: 80 },
            terminals: [
              { id: 'in', name: 'in', offset: { x: -40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] },
              { id: 'out', name: 'out', offset: { x: 40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] }
            ],
            operation: { switchState: 'closed', tripped: false }
          }),
          symbol({
            id: 'cb-b',
            type: 'circuit-breaker',
            position: { x: 180, y: 80 },
            terminals: [
              { id: 'in', name: 'in', offset: { x: -40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] },
              { id: 'out', name: 'out', offset: { x: 40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] }
            ],
            operation: { switchState: 'closed', tripped: false }
          })
        ],
        conductors: [],
        busbars: [],
        labels: [],
        annotations: []
      }
    })!;

    const snapshots = buildSequenceSnapshots(finalDoc, sequence);
    expect(snapshots).toHaveLength(3);
    expect(snapshots[0].beginSeconds).toBe(0);
    expect(snapshots[1].beginSeconds).toBe(SEQUENCE_INTRO_SECONDS);
    expect(snapshots[0].doc.objects.symbols.every((item) => item.operation?.switchState === 'open')).toBe(true);
    expect(snapshots[1].doc.objects.symbols.find((item) => item.id === 'cb-a')?.operation?.switchState).toBe('closed');
    expect(snapshots[1].doc.objects.symbols.find((item) => item.id === 'cb-b')?.operation?.switchState).toBe('open');
    expect(snapshots[2].doc.objects.symbols.every((item) => item.operation?.switchState === 'closed')).toBe(true);
  });
});
