import { describe, expect, it } from 'vitest';
import type { DrawingDocument, ElectricalSymbol } from '../drawing/model';
import { migrateDrawingDocument } from '../schema/documentSchema';
import { deriveOperationState } from '../topology/operation';
import { extractTopology } from '../topology/extractTopology';
import { resolveSwitchgearVisualState } from '../rendering/switchgearVisualState';

const symbol = (patch: Partial<ElectricalSymbol> & Pick<ElectricalSymbol, 'id' | 'type' | 'position' | 'terminals'>): ElectricalSymbol => ({
  rotation: 0,
  phaseApplicability: ['A', 'B', 'C'],
  simulation: {},
  operation: { switchState: 'open', tripped: false },
  label: { text: patch.id, autoGenerated: true, manualOverride: false },
  ...patch
});

describe('resolveSwitchgearVisualState', () => {
  it('marks open switchgear as open and live closed switchgear as closed-live', () => {
    const doc = migrateDrawingDocument({
      id: 'doc-1',
      version: 2,
      name: 'Switchgear test',
      activeView: 'single-line',
      objects: {
        symbols: [
          symbol({
            id: 'source-1',
            type: 'source',
            position: { x: 0, y: 0 },
            terminals: [{ id: 'out', name: 'out', offset: { x: 40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] }],
            operation: { sourceOn: true, tripped: false }
          }),
          symbol({
            id: 'cb-open',
            type: 'circuit-breaker',
            position: { x: 70, y: 0 },
            terminals: [
              { id: 'in', name: 'in', offset: { x: -30, y: 0 }, phaseApplicability: ['A', 'B', 'C'] },
              { id: 'out', name: 'out', offset: { x: 30, y: 0 }, phaseApplicability: ['A', 'B', 'C'] }
            ]
          }),
          symbol({
            id: 'cb-closed',
            type: 'circuit-breaker',
            position: { x: 140, y: 0 },
            terminals: [
              { id: 'in', name: 'in', offset: { x: -30, y: 0 }, phaseApplicability: ['A', 'B', 'C'] },
              { id: 'out', name: 'out', offset: { x: 30, y: 0 }, phaseApplicability: ['A', 'B', 'C'] }
            ],
            operation: { switchState: 'closed', tripped: false }
          }),
          symbol({
            id: 'load-1',
            type: 'load',
            position: { x: 210, y: 0 },
            terminals: [{ id: 'in', name: 'in', offset: { x: -40, y: 0 }, phaseApplicability: ['A', 'B', 'C'] }]
          })
        ],
        conductors: [],
        busbars: [{
          id: 'bus-1',
          type: 'busbar-segment',
          rotation: 0,
          phaseApplicability: ['A', 'B', 'C'],
          width: 8,
          vertices: [{ x: 40, y: 0 }, { x: 110, y: 0 }, { x: 180, y: 0 }, { x: 250, y: 0 }],
          connectionPoints: [
            { id: 'bus-1-cp-0', position: { x: 40, y: 0 } },
            { id: 'bus-1-cp-1', position: { x: 110, y: 0 } },
            { id: 'bus-1-cp-2', position: { x: 180, y: 0 } },
            { id: 'bus-1-cp-3', position: { x: 250, y: 0 } }
          ]
        }],
        labels: [],
        annotations: []
      }
    }) as DrawingDocument;

    const topology = extractTopology(doc);
    const operateState = deriveOperationState(doc, topology);
    const openBreaker = doc.objects.symbols.find((item) => item.id === 'cb-open')!;
    const closedBreaker = doc.objects.symbols.find((item) => item.id === 'cb-closed')!;

    expect(resolveSwitchgearVisualState(openBreaker, topology, operateState)).toBe('open');
    expect(resolveSwitchgearVisualState(closedBreaker, topology, operateState)).toBe('closed-live');
  });
});
