export type Phase = 'A' | 'B' | 'C' | 'N' | 'E';

export type ViewMode = 'single-line' | 'three-phase';

export interface Point {
  x: number;
  y: number;
}

export interface Terminal {
  id: string;
  name: string;
  offset: Point;
  phaseApplicability: Phase[];
}

export interface ConnectionPoint {
  id: string;
  position: Point;
  snappedTo?: {
    objectId: string;
    terminalId?: string;
    conductorId?: string;
  };
}

export interface LabelMetadata {
  text: string;
  autoGenerated: boolean;
  manualOverride: boolean;
  marker?: string;
}

export interface SimulationMetadata {
  role?: 'source' | 'load' | 'feeder' | 'switching' | 'measurement';
  interlockGroupIds?: string[];
  damaged?: boolean;
  faulted?: boolean;
}

export type PhaseMode = 'single-phase' | 'three-phase';
export type RenderExpansion = 'single-symbol' | 'per-phase-symbols';
export type FlowDirection = 'forward' | 'reverse' | 'bidirectional' | 'unknown';
export type FaultType =
  | 'phase-to-earth'
  | 'phase-to-phase'
  | 'three-phase'
  | 'open-circuit'
  | 'high-impedance'
  | 'transient'
  | 'persistent'
  | 'A-E'
  | 'B-E'
  | 'C-E'
  | 'A-B'
  | 'B-C'
  | 'C-A'
  | 'A-B-C'
  | 'A-B-C-E'
  | 'hot-joint';

export type ThermalState = 'normal' | 'warm' | 'hot' | 'critical';
export type ProtectionElementType = 'overcurrent' | 'earth-fault' | 'thermal-overload' | 'breaker-fail' | 'differential';
export type ProtectionRuntimeState = 'idle' | 'picked-up' | 'tripped';
export type RelayLogicType = 'overcurrent' | 'earth-fault';

export interface PhaseElectricalValues {
  mw?: number;
  mvar?: number;
  mva?: number;
  currentA?: number;
  voltageKv?: number;
  voltageDropKv?: number;
  resistanceOhms?: number;
  reactanceOhms?: number;
  impedanceOhms?: number;
  powerFactor?: number;
  direction?: FlowDirection;
  loadingPercent?: number;
  temperatureC?: number;
  thermalState?: ThermalState;
  alarmState?: 'normal' | 'warning' | 'alarm' | 'trip';
  protectionState?: ProtectionRuntimeState;
  manualOverride?: boolean;
}

export interface PowerFlowMetadata {
  mw?: number;
  mvar?: number;
  mva?: number;
  currentA?: number;
  voltageKv?: number;
  voltageDropKv?: number;
  resistanceOhms?: number;
  reactanceOhms?: number;
  impedanceOhms?: number;
  powerFactor?: number;
  direction?: FlowDirection;
  loadingPercent?: number;
  temperatureC?: number;
  thermalState?: ThermalState;
  manualOverride?: boolean;
  perPhase?: Partial<Record<Phase, PhaseElectricalValues>>;
}

export interface FaultMetadata {
  id: string;
  targetObjectId?: string;
  targetTerminalId?: string;
  targetTopologyNodeId?: string;
  targetTopologyBranchId?: string;
  targetPhase?: Phase;
  location?: Point;
  locationRatio?: number;
  phases: Phase[];
  type: FaultType;
  persistent: boolean;
  durationMs?: number;
  resistanceOhms?: number;
  active: boolean;
  label?: string;
  note?: string;
  createdAt: string;
}

export interface HotJointMetadata {
  id: string;
  targetObjectId?: string;
  targetTerminalId?: string;
  targetTopologyNodeId?: string;
  targetTopologyBranchId?: string;
  phase: Phase;
  addedResistanceOhms: number;
  thermalMassFactor: number;
  ambientTemperatureC: number;
  warningTemperatureC: number;
  dangerTemperatureC: number;
  intermittent: boolean;
  active: boolean;
  label?: string;
}

export interface ProtectionElement {
  id: string;
  type: ProtectionElementType;
  enabled: boolean;
  watchedObjectId?: string;
  watchedTopologyBranchId?: string;
  watchedTopologyNodeId?: string;
  phases: Phase[];
  pickupCurrentA?: number;
  timeDelayMs?: number;
  tripTargetBreakerIds: string[];
  state: ProtectionRuntimeState;
  pickedUpAt?: string;
  trippedAt?: string;
}

export interface ProtectionZone {
  id: string;
  name: string;
  vertices: Point[];
  assignedObjectIds: string[];
  ctInputIds: string[];
  vtInputIds: string[];
  color: string;
  visible: boolean;
}

export interface RelaySettings {
  id: string;
  name: string;
  zoneId?: string;
  type: RelayLogicType;
  enabled: boolean;
  phases: Phase[];
  pickupCurrentA: number;
  earthFaultPickupA?: number;
  timeDelayMs: number;
  directional: boolean;
  tripTargetBreakerIds: string[];
  backupTripTargetBreakerIds: string[];
  breakerFailEnabled: boolean;
  breakerFailDelayMs: number;
  state: ProtectionRuntimeState;
  pickedUpAt?: string;
  trippedAt?: string;
  resetAt?: string;
}

export interface ScenarioObjective {
  id: string;
  text: string;
  targetObjectId?: string;
  completed?: boolean;
}

export interface ScenarioDefinition {
  id: string;
  name: string;
  description?: string;
  initialSwitchStates: Record<string, 'open' | 'closed'>;
  initialSourceStates: Record<string, boolean>;
  faults: FaultMetadata[];
  relays: RelaySettings[];
  objectives: ScenarioObjective[];
}

export interface SimulationControlState {
  running: boolean;
  speed: number;
  overlay: 'none' | 'topology' | 'thermal';
  lastRecomputedAt?: string;
}

export interface OperationEvent {
  id: string;
  timestamp: string;
  message: string;
  targetObjectId?: string;
  reason?: string;
}

export interface BaseDrawingObject {
  id: string;
  type: string;
  rotation: number;
  phaseApplicability: Phase[];
  voltageLevelKv?: number;
  layerId?: string;
  viewMetadata?: Record<ViewMode, { visible: boolean }>;
  label?: LabelMetadata;
  simulation?: SimulationMetadata;
  phaseMode?: PhaseMode;
  renderExpansion?: RenderExpansion;
  phaseSpacingPx?: number;
  powerFlow?: PowerFlowMetadata;
  operation?: {
    switchState?: 'open' | 'closed';
    perPhaseSwitchState?: Partial<Record<Phase, 'open' | 'closed'>>;
    sourceOn?: boolean;
    tripped?: boolean;
    protectionState?: ProtectionRuntimeState;
  };
}

export interface ElectricalSymbol extends BaseDrawingObject {
  type:
    | 'source'
    | 'load'
    | 'busbar-coupler'
    | 'circuit-breaker'
    | 'disconnector'
    | 'earth-switch'
    | 'transformer'
    | 'vt'
    | 'ct'
    | 'cable-sealing-end'
    | 'line-end';
  position: Point;
  terminals: Terminal[];
  symbolVariant?: string;
  engineering?: {
    ctPolarity?: 'P1-left' | 'P1-right';
    transformerPolarity?: 'hv-left' | 'hv-right';
    hasTertiary?: boolean;
    tertiaryVoltageKv?: number;
    transformerExpansion?: 'single-symbol' | 'three-phase-expanded';
  };
}

export interface ConductorPath extends BaseDrawingObject {
  type: 'conductor-path';
  vertices: Point[];
  orthogonal: boolean;
  connectionPoints: ConnectionPoint[];
}

export interface BusbarSegment extends BaseDrawingObject {
  type: 'busbar-segment';
  vertices: Point[];
  width: number;
  connectionPoints: ConnectionPoint[];
}

export interface Label {
  id: string;
  type: 'label';
  position: Point;
  text: string;
  forObjectId?: string;
}

export interface Annotation {
  id: string;
  type: 'annotation';
  position: Point;
  text: string;
}

export interface DrawingDocument {
  id: string;
  version: 2;
  schemaVersion: number;
  name: string;
  activeView: ViewMode;
  objects: {
    symbols: ElectricalSymbol[];
    conductors: ConductorPath[];
    busbars: BusbarSegment[];
    labels: Label[];
    annotations: Annotation[];
  };
  faults: FaultMetadata[];
  hotJoints: HotJointMetadata[];
  protectionZones: ProtectionZone[];
  relays: RelaySettings[];
  protection: ProtectionElement[];
  scenarios: ScenarioDefinition[];
  activeScenarioId?: string;
  operationEvents: OperationEvent[];
  simulationState: SimulationControlState;
  uiState: {
    gridSize: number;
    snapToGrid: boolean;
    snapToTerminals: boolean;
    snapToIntersections: boolean;
  };
  history?: {
    undoStack: string[];
    redoStack: string[];
  };
}
