export type Phase = 'A' | 'B' | 'C' | 'N' | 'E';

export type ViewMode = 'single-line' | 'three-phase';

export interface Point {
  x: number;
  y: number;
}

export interface Terminal {
  id: string;
  name: string;
  offset: Point;
  phaseApplicability: Phase[];
}

export interface ConnectionPoint {
  id: string;
  position: Point;
  snappedTo?: {
    objectId: string;
    terminalId?: string;
    conductorId?: string;
  };
}

export type BusbarRole = 'main' | 'reserve' | 'main-1' | 'reserve-1' | 'main-2' | 'reserve-2';

export interface Bp109LabelHints {
  circuitType?: string;
  circuitNumber?: number;
  purposeDigit?: number;
  prefix?: string;
  suffixLetter?: string;
}

export interface LabelMetadata {
  text: string;
  autoGenerated: boolean;
  manualOverride: boolean;
  marker?: string;
}

export interface SimulationMetadata {
  role?: 'source' | 'load' | 'feeder' | 'switching' | 'measurement';
  interlockGroupIds?: string[];
  damaged?: boolean;
  faulted?: boolean;
  identified?: boolean;
  arced?: boolean;
}

export type PhaseMode = 'single-phase' | 'three-phase';
export type RenderExpansion = 'single-symbol' | 'per-phase-symbols';
export type FlowDirection = 'forward' | 'reverse' | 'bidirectional' | 'unknown';
export type FaultType =
  | 'phase-to-earth'
  | 'phase-to-phase'
  | 'three-phase'
  | 'open-circuit'
  | 'high-impedance'
  | 'transient'
  | 'persistent'
  | 'A-E'
  | 'B-E'
  | 'C-E'
  | 'A-B'
  | 'B-C'
  | 'C-A'
  | 'A-B-C'
  | 'A-B-C-E'
  | 'hot-joint';

export type ThermalState = 'normal' | 'warm' | 'hot' | 'critical';
export type ProtectionElementType = 'overcurrent' | 'earth-fault' | 'thermal-overload' | 'breaker-fail' | 'differential';
export type ProtectionRuntimeState = 'idle' | 'picked-up' | 'tripped' | 'blocked' | 'disabled' | 'failed';
export type RelayLogicType = 'overcurrent' | 'earth-fault';
export type RelayRole = 'first-main' | 'second-main' | 'backup' | 'busbar-protection' | 'transformer-protection' | 'feeder-protection' | 'motor-load-protection';
export type RelayInputSourceType = 'ct' | 'vt' | 'transformer-winding' | 'busbar' | 'conductor' | 'feeder-load-source' | 'topology-node' | 'zone';
export type RelayMeasuredQuantity = 'current' | 'voltage' | 'power' | 'earth-residual-current' | 'differential-current' | 'temperature' | 'frequency';
export type RelayFunctionType =
  | 'overcurrent'
  | 'earth-fault'
  | 'directional-overcurrent'
  | 'directional-earth-fault'
  | 'overvoltage'
  | 'undervoltage'
  | 'thermal-overload'
  | 'differential'
  | 'restricted-earth-fault'
  | 'breaker-fail'
  | 'intertrip'
  | 'trip-circuit-supervision';
export type RelayFunctionState = 'inactive' | 'picked-up' | 'timing' | 'tripped' | 'reset';
export type RelayLogicCondition = 'any-phase' | 'all-phases' | 'selected-phase' | 'residual-earth' | 'differential-between-inputs';
export type RelayOutputTargetType = 'circuit-breaker' | 'disconnector' | 'source' | 'alarm' | 'lockout' | 'intertrip-target' | 'event-log';
export type RelayOutputActionType = 'trip-open-breaker' | 'block-close' | 'alarm' | 'apply-lockout' | 'clear-auto-reset' | 'trigger-backup-relay';

export interface PhaseElectricalValues {
  mw?: number;
  mvar?: number;
  mva?: number;
  currentA?: number;
  voltageKv?: number;
  voltageDropKv?: number;
  resistanceOhms?: number;
  reactanceOhms?: number;
  impedanceOhms?: number;
  powerFactor?: number;
  direction?: FlowDirection;
  loadingPercent?: number;
  temperatureC?: number;
  thermalState?: ThermalState;
  alarmState?: 'normal' | 'warning' | 'alarm' | 'trip';
  protectionState?: ProtectionRuntimeState;
  manualOverride?: boolean;
}

export interface PowerFlowMetadata {
  mw?: number;
  mvar?: number;
  mva?: number;
  currentA?: number;
  voltageKv?: number;
  voltageDropKv?: number;
  resistanceOhms?: number;
  reactanceOhms?: number;
  impedanceOhms?: number;
  powerFactor?: number;
  direction?: FlowDirection;
  loadingPercent?: number;
  temperatureC?: number;
  thermalState?: ThermalState;
  manualOverride?: boolean;
  perPhase?: Partial<Record<Phase, PhaseElectricalValues>>;
}

export interface FaultMetadata {
  id: string;
  targetObjectId?: string;
  targetTerminalId?: string;
  targetTopologyNodeId?: string;
  targetTopologyBranchId?: string;
  targetPhase?: Phase;
  location?: Point;
  locationRatio?: number;
  phases: Phase[];
  type: FaultType;
  persistent: boolean;
  durationMs?: number;
  resistanceOhms?: number;
  active: boolean;
  label?: string;
  note?: string;
  createdAt: string;
}

export interface HotJointMetadata {
  id: string;
  targetObjectId?: string;
  targetTerminalId?: string;
  targetTopologyNodeId?: string;
  targetTopologyBranchId?: string;
  phase: Phase;
  addedResistanceOhms: number;
  thermalMassFactor: number;
  ambientTemperatureC: number;
  warningTemperatureC: number;
  dangerTemperatureC: number;
  intermittent: boolean;
  active: boolean;
  label?: string;
}

export interface ProtectionElement {
  id: string;
  type: ProtectionElementType;
  enabled: boolean;
  watchedObjectId?: string;
  watchedTopologyBranchId?: string;
  watchedTopologyNodeId?: string;
  phases: Phase[];
  pickupCurrentA?: number;
  timeDelayMs?: number;
  tripTargetBreakerIds: string[];
  state: ProtectionRuntimeState;
  pickedUpAt?: string;
  trippedAt?: string;
}

export interface ProtectionZone {
  id: string;
  name: string;
  vertices: Point[];
  assignedObjectIds: string[];
  ctInputIds: string[];
  vtInputIds: string[];
  color: string;
  visible: boolean;
}

export interface RelayInput {
  id: string;
  sourceType: RelayInputSourceType;
  sourceObjectId?: string;
  sourceTopologyNodeId?: string;
  sourceZoneId?: string;
  sourceLabel?: string;
  phases: Phase[];
  quantity: RelayMeasuredQuantity;
  polarity?: 'forward' | 'reverse' | 'none';
  ctRatio?: string;
  vtRatio?: string;
}

export interface RelayFunction {
  id: string;
  type: RelayFunctionType;
  enabled: boolean;
  pickupThreshold?: number;
  resetThreshold?: number;
  timeDelayMs: number;
  instantaneous: boolean;
  phases: Phase[];
  requiredInputType?: RelayMeasuredQuantity;
  logic: RelayLogicCondition;
  state: RelayFunctionState;
  pickedUpAt?: string;
  trippedAt?: string;
}

export interface RelayOutputAction {
  id: string;
  targetType: RelayOutputTargetType;
  targetObjectId?: string;
  action: RelayOutputActionType;
  delayMs?: number;
  warning?: string;
}

export interface RelayEvent {
  id: string;
  timestamp: string;
  message: string;
  functionId?: string;
  targetObjectId?: string;
}

export interface RelaySettings {
  id: string;
  name: string;
  zoneId?: string;
  role?: RelayRole;
  protectedAssetId?: string;
  type: RelayLogicType;
  enabled: boolean;
  phases: Phase[];
  pickupCurrentA: number;
  earthFaultPickupA?: number;
  timeDelayMs: number;
  directional: boolean;
  tripTargetBreakerIds: string[];
  backupTripTargetBreakerIds: string[];
  breakerFailEnabled: boolean;
  breakerFailDelayMs: number;
  state: ProtectionRuntimeState;
  pickedUpAt?: string;
  trippedAt?: string;
  resetAt?: string;
  inputs?: RelayInput[];
  functions?: RelayFunction[];
  outputActions?: RelayOutputAction[];
  eventHistory?: RelayEvent[];
}

export interface ScenarioObjective {
  id: string;
  text: string;
  type?:
    | 'energise-target-busbar'
    | 'isolate-faulted-section'
    | 'restore-supply-to-load'
    | 'operate-switchgear'
    | 'avoid-disconnector-under-load'
    | 'clear-fault-using-breaker'
    | 'identify-faulted-component'
    | 'identify-hot-joint'
    | 'explain-protection-trip'
    | 'maintain-no-live-earth-conflict';
  targetObjectId?: string;
  targetTopologyNodeId?: string;
  targetTopologyBranchId?: string;
  targetState?: 'open' | 'closed' | 'live' | 'dead' | 'isolated' | 'cleared' | 'identified';
  hint?: string;
  tierText?: Partial<Record<LearningTier, string>>;
  tierHints?: Partial<Record<LearningTier, string>>;
  completed?: boolean;
  failed?: boolean;
}

export type ScenarioDifficulty = 'intro' | 'standard' | 'advanced';
export type ScenarioEventType = 'scheduled-fault' | 'transient-fault' | 'load-increase' | 'source-trip' | 'breaker-fail' | 'relay-pickup-trip' | 'operator-prompt' | 'hint-popup';
export type ScenarioMode = 'lesson' | 'challenge' | 'sandbox';
export type ScenarioEventSeverity = 'info' | 'operation' | 'warning' | 'protection' | 'alarm' | 'fault' | 'scenario';
export type LearningTier = 'Junior' | 'Student' | 'Apprentice' | 'Engineer' | 'Commissioning Engineer';

export interface ScenarioEvent {
  id: string;
  type: ScenarioEventType;
  atMs: number;
  targetObjectId?: string;
  fault?: FaultMetadata;
  loadMw?: number;
  sourceOn?: boolean;
  message?: string;
  hint?: string;
  fired?: boolean;
}

export interface ScenarioSuccessRules {
  targetEnergisedObjectIds?: string[];
  isolatedFaultObjectIds?: string[];
  restoredLoadObjectIds?: string[];
  requiredSwitchStates?: Record<string, 'open' | 'closed'>;
  maxWrongOperations?: number;
  requireNoLiveEarthConflict?: boolean;
  requireVoltageSegregation?: boolean;
  requiredSequence?: string[];
  requireAlarmsCleared?: boolean;
  keepSuppliedObjectIds?: string[];
  requireNoDamagedEquipment?: boolean;
  timeLimitMs?: number;
}

export interface ScenarioRestrictions {
  disableDrawingTools?: boolean;
  disablePlacement?: boolean;
  disableDelete?: boolean;
  disableTopologyOverlay?: boolean;
  disableInspectorEditing?: boolean;
  allowedTools?: string[];
  allowedComponentTypes?: ElectricalSymbol['type'][];
  allowedOperationObjectIds?: string[];
}

export interface ScenarioTeachingStep {
  id: string;
  title: string;
  body: string;
  targetObjectId?: string;
  waitFor?: 'operation' | 'correct-state' | 'fault-clearance' | 'target-energised' | 'manual';
  expectedObjectId?: string;
  expectedState?: 'open' | 'closed' | 'live' | 'dead' | 'cleared';
  pauseSimulation?: boolean;
  unlockTool?: string;
  eventIdToTrigger?: string;
}

export interface ScenarioScoring {
  stars?: number;
  score?: number;
  operationCount?: number;
  penalties?: number;
  speedBonus?: number;
  safetyBonus?: number;
  noTripBonus?: number;
  noIncorrectOperationBonus?: number;
}

export interface ScenarioBriefing {
  expectedOperatorRole?: string;
  initialCondition?: string;
  restrictions?: string[];
  warnings?: string[];
  winConditions?: string[];
  loseConditions?: string[];
  estimatedMinutes?: number;
}

export interface ScenarioReplayStep {
  id: string;
  atMs: number;
  action: 'operate' | 'hint' | 'prompt' | 'reset' | 'event';
  targetObjectId?: string;
  message: string;
}

export interface ScenarioDefinition {
  id: string;
  name: string;
  description?: string;
  learningObjectives?: string[];
  minTier?: LearningTier;
  maxTier?: LearningTier;
  recommendedTier?: LearningTier;
  supportedTiers?: LearningTier[];
  explanationVariants?: Partial<Record<LearningTier, string>>;
  mode?: ScenarioMode;
  difficulty?: ScenarioDifficulty;
  tags?: string[];
  briefing?: ScenarioBriefing;
  restrictions?: ScenarioRestrictions;
  teachingSteps?: ScenarioTeachingStep[];
  currentStepIndex?: number;
  scoring?: ScenarioScoring;
  completionRating?: number;
  initialSwitchStates: Record<string, 'open' | 'closed'>;
  initialSourceStates: Record<string, boolean>;
  faults: FaultMetadata[];
  relays: RelaySettings[];
  protection?: ProtectionElement[];
  powerFlows?: Record<string, PowerFlowMetadata>;
  activeView?: ViewMode | 'thermal' | 'topology';
  objectives: ScenarioObjective[];
  tierObjectives?: Partial<Record<LearningTier, ScenarioObjective[]>>;
  events?: ScenarioEvent[];
  successRules?: ScenarioSuccessRules;
  failureRules?: ScenarioSuccessRules;
  expectedSolution?: ScenarioReplayStep[];
  replayLog?: ScenarioReplayStep[];
  startedAt?: string;
  elapsedMs?: number;
  wrongOperationCount?: number;
  currentHintIndex?: number;
}

export interface SimulationControlState {
  running: boolean;
  speed: number;
  overlay: 'none' | 'topology' | 'thermal';
  lastRecomputedAt?: string;
}

export interface OperationEvent {
  id: string;
  timestamp: string;
  message: string;
  targetObjectId?: string;
  reason?: string;
  severity?: ScenarioEventSeverity;
  source?: string;
}

export interface BaseDrawingObject {
  id: string;
  type: string;
  rotation: number;
  phaseApplicability: Phase[];
  voltageLevelKv?: number;
  layerId?: string;
  viewMetadata?: Record<ViewMode, { visible: boolean }>;
  label?: LabelMetadata;
  simulation?: SimulationMetadata;
  phaseMode?: PhaseMode;
  renderExpansion?: RenderExpansion;
  phaseSpacingPx?: number;
  powerFlow?: PowerFlowMetadata;
  operation?: {
    switchState?: 'open' | 'closed';
    perPhaseSwitchState?: Partial<Record<Phase, 'open' | 'closed'>>;
    sourceOn?: boolean;
    tripped?: boolean;
    lockout?: boolean;
    protectionState?: ProtectionRuntimeState;
  };
}

export interface ElectricalSymbol extends BaseDrawingObject {
  type:
    | 'source'
    | 'load'
    | 'grid-connection'
    | 'busbar-coupler'
    | 'circuit-breaker'
    | 'disconnector'
    | 'earth-switch'
    | 'transformer'
    | 'vt'
    | 'ct'
    | 'cable-sealing-end'
    | 'line-end';
  position: Point;
  terminals: Terminal[];
  symbolVariant?: string;
  engineering?: {
    ctPolarity?: 'P1-left' | 'P1-right';
    transformerPolarity?: 'hv-left' | 'hv-right';
    hasTertiary?: boolean;
    tertiaryVoltageKv?: number;
    transformerExpansion?: 'single-symbol' | 'three-phase-expanded';
    bp109?: Bp109LabelHints & { circuitType?: string };
    busbarRole?: BusbarRole;
  };
}

export interface ConductorPath extends BaseDrawingObject {
  type: 'conductor-path';
  conductorStyle?: 'cable' | 'overhead-line';
  vertices: Point[];
  orthogonal: boolean;
  connectionPoints: ConnectionPoint[];
}

export interface BusbarSegment extends BaseDrawingObject {
  type: 'busbar-segment';
  vertices: Point[];
  width: number;
  connectionPoints: ConnectionPoint[];
  engineering?: {
    busbarRole?: BusbarRole;
  };
}

export interface Label {
  id: string;
  type: 'label';
  position: Point;
  text: string;
  forObjectId?: string;
}

export interface Annotation {
  id: string;
  type: 'annotation';
  position: Point;
  text: string;
}

export interface DrawingDocument {
  id: string;
  version: 2;
  schemaVersion: number;
  name: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
  drawingType: 'user' | 'template' | 'example';
  tags: string[];
  voltageLevels: number[];
  thumbnail?: string;
  lastOpenedAt?: string;
  templateNotes?: string;
  activeView: ViewMode;
  objects: {
    symbols: ElectricalSymbol[];
    conductors: ConductorPath[];
    busbars: BusbarSegment[];
    labels: Label[];
    annotations: Annotation[];
  };
  faults: FaultMetadata[];
  hotJoints: HotJointMetadata[];
  protectionZones: ProtectionZone[];
  relays: RelaySettings[];
  protection: ProtectionElement[];
  scenarios: ScenarioDefinition[];
  activeScenarioId?: string;
  operationEvents: OperationEvent[];
  simulationState: SimulationControlState;
  uiState: {
    gridSize: number;
    snapToGrid: boolean;
    snapToTerminals: boolean;
    snapToIntersections: boolean;
    labelScheme?: 'DEFAULT' | 'NG_BP109' | 'ANSI_IEC';
    displayScale?: {
      busbar?: number;
      text?: number;
      symbol?: number;
    };
  };
  history?: {
    undoStack: string[];
    redoStack: string[];
  };
}
