import type { BusbarSegment, ConductorPath, DrawingDocument, ElectricalSymbol, FaultMetadata, HotJointMetadata, Phase, Point, ProtectionElement, ProtectionZone, RelaySettings } from '../drawing/model';
import { MIMIC_DESIGNER_V2_SCHEMA_VERSION, migrateDrawingDocument } from '../schema/documentSchema';
import { SWITCH_TERMINAL_SPAN } from '../symbols/library';

export interface DrawingTemplate {
  id: string;
  name: string;
  description: string;
  category: 'template' | 'example';
  tags: string[];
  voltageLevels: number[];
  notes?: string;
  create: () => DrawingDocument;
}

const phases = ['A', 'B', 'C'] as Phase[];
const phaseSpacingPx = 150;

export function createBaseDocument(id: string, name: string, patch: Partial<DrawingDocument> = {}): DrawingDocument {
  const now = new Date().toISOString();
  return migrateDrawingDocument({
    id,
    version: 2,
    schemaVersion: MIMIC_DESIGNER_V2_SCHEMA_VERSION,
    name,
    description: patch.description ?? '',
    createdAt: patch.createdAt ?? now,
    updatedAt: patch.updatedAt ?? now,
    drawingType: patch.drawingType ?? 'template',
    tags: patch.tags ?? [],
    voltageLevels: patch.voltageLevels ?? [132],
    templateNotes: patch.templateNotes,
    activeView: patch.activeView ?? 'single-line',
    objects: patch.objects ?? { symbols: [], conductors: [], busbars: [], labels: [], annotations: [] },
    faults: patch.faults ?? [],
    hotJoints: patch.hotJoints ?? [],
    protectionZones: patch.protectionZones ?? [],
    relays: patch.relays ?? [],
    protection: patch.protection ?? [],
    scenarios: patch.scenarios ?? [],
    operationEvents: [],
    simulationState: { running: false, speed: 1, overlay: 'none' },
    uiState: { gridSize: 20, snapToGrid: true, snapToTerminals: true, snapToIntersections: true }
  })!;
}

export function symbol(id: string, type: ElectricalSymbol['type'], x: number, y: number, label: string, voltageLevelKv = 132, rotation = 0, patch: Partial<ElectricalSymbol> = {}): ElectricalSymbol {
  const terminalDefs = terminalsFor(type);
  return {
    id,
    type,
    position: { x, y },
    rotation,
    terminals: terminalDefs.map((terminal, index) => ({ id: terminalId(terminal, index), name: terminal.name, offset: { x: terminal.x, y: terminal.y }, phaseApplicability: patch.phaseApplicability ?? phases })),
    phaseApplicability: patch.phaseApplicability ?? phases,
    voltageLevelKv,
    phaseMode: 'three-phase',
    renderExpansion: 'per-phase-symbols',
    phaseSpacingPx,
    label: { text: label, autoGenerated: false, manualOverride: true },
    simulation: {},
    operation: {
      sourceOn: type === 'source' ? true : undefined,
      switchState: ['circuit-breaker', 'disconnector', 'earth-switch'].includes(type) ? patch.operation?.switchState ?? 'open' : undefined,
      tripped: false,
      ...patch.operation
    },
    powerFlow: type === 'source' ? { mw: 30, mvar: 10, voltageKv: voltageLevelKv, direction: 'forward', ...patch.powerFlow } : patch.powerFlow,
    engineering: type === 'ct' ? { ctPolarity: 'P1-left', ...patch.engineering } : type === 'transformer' ? { transformerPolarity: 'hv-left', hasTertiary: false, transformerExpansion: 'single-symbol', ...patch.engineering } : patch.engineering,
    viewMetadata: { 'single-line': { visible: true }, 'three-phase': { visible: true } },
    ...patch
  };
}

export function busbar(id: string, vertices: Point[], voltageLevelKv = 132): BusbarSegment {
  return {
    id,
    type: 'busbar-segment',
    rotation: 0,
    phaseApplicability: phases,
    voltageLevelKv,
    phaseMode: 'three-phase',
    renderExpansion: 'per-phase-symbols',
    phaseSpacingPx,
    width: 8,
    vertices,
    orthogonal: true,
    connectionPoints: vertices.map((position, index) => ({ id: `${id}-cp-${index}`, position }))
  } as BusbarSegment;
}

export function conductor(id: string, vertices: Point[], voltageLevelKv = 132, conductorStyle: ConductorPath['conductorStyle'] = 'cable'): ConductorPath {
  return {
    id,
    type: 'conductor-path',
    conductorStyle,
    rotation: 0,
    phaseApplicability: phases,
    voltageLevelKv,
    phaseMode: 'three-phase',
    renderExpansion: 'per-phase-symbols',
    phaseSpacingPx,
    vertices,
    orthogonal: true,
    connectionPoints: vertices.map((position, index) => ({ id: `${id}-cp-${index}`, position }))
  };
}

export function feederChain(prefix: string, y: number, startX: number, labelPrefix: string, voltage = 132, closed = true) {
  const source = symbol(`${prefix}-source`, 'source', startX, y, `${labelPrefix} SRC`, voltage);
  const es1 = symbol(`${prefix}-es1`, 'earth-switch', startX + 120, y + 90, `${labelPrefix} ES1`, voltage);
  const ds1 = symbol(`${prefix}-ds1`, 'disconnector', startX + 220, y, `${labelPrefix} DS1`, voltage, 0, { operation: { switchState: closed ? 'closed' : 'open' } });
  const cb = symbol(`${prefix}-cb`, 'circuit-breaker', startX + 380, y, `${labelPrefix} CB`, voltage, 0, { operation: { switchState: closed ? 'closed' : 'open' } });
  const ct = symbol(`${prefix}-ct`, 'ct', startX + 530, y, `${labelPrefix} CT`, voltage);
  const ds2 = symbol(`${prefix}-ds2`, 'disconnector', startX + 690, y, `${labelPrefix} DS2`, voltage, 0, { operation: { switchState: closed ? 'closed' : 'open' } });
  const es2 = symbol(`${prefix}-es2`, 'earth-switch', startX + 830, y + 90, `${labelPrefix} ES2`, voltage);
  const vt = symbol(`${prefix}-vt`, 'vt', startX + 980, y + 110, `${labelPrefix} VT`, voltage);
  const load = symbol(`${prefix}-load`, 'load', startX + 1110, y, `${labelPrefix} LINE`, voltage);
  return {
    symbols: [source, es1, ds1, cb, ct, ds2, es2, vt, load],
    busbars: [busbar(`${prefix}-bus`, [{ x: startX + 720, y }, { x: startX + 830, y }, { x: startX + 980, y }, { x: startX + 1070, y }], voltage)],
    conductors: [
      conductor(`${prefix}-source-ds1`, [{ x: startX + 40, y }, { x: startX + 120, y }, { x: startX + 220 - SWITCH_TERMINAL_SPAN, y }], voltage, 'overhead-line'),
      conductor(`${prefix}-ds1-cb`, [{ x: startX + 220 + SWITCH_TERMINAL_SPAN, y }, { x: startX + 380 - SWITCH_TERMINAL_SPAN, y }], voltage, 'overhead-line'),
      conductor(`${prefix}-cb-ct`, [{ x: startX + 380 + SWITCH_TERMINAL_SPAN, y }, { x: startX + 530 - 20, y }], voltage, 'overhead-line'),
      conductor(`${prefix}-ct-ds2`, [{ x: startX + 530 + 20, y }, { x: startX + 690 - SWITCH_TERMINAL_SPAN, y }], voltage, 'overhead-line'),
      conductor(`${prefix}-es1-tap`, [{ x: startX + 120, y }, { x: startX + 120, y: y + 90 }], voltage, 'overhead-line'),
      conductor(`${prefix}-es2-tap`, [{ x: startX + 830, y }, { x: startX + 830, y: y + 90 }], voltage, 'overhead-line'),
      conductor(`${prefix}-vt-tap`, [{ x: startX + 980, y }, { x: startX + 980, y: y + 70 }, { x: startX + 980, y: y + 110 }], voltage, 'overhead-line')
    ]
  };
}

export function zone(id: string, name: string, assignedObjectIds: string[], vertices: Point[], color = '#22c55e'): ProtectionZone {
  return { id, name, vertices, assignedObjectIds, ctInputIds: assignedObjectIds.filter((item) => item.includes('ct')), vtInputIds: assignedObjectIds.filter((item) => item.includes('vt')), color, visible: true };
}

export function relay(id: string, name: string, type: RelaySettings['type'], zoneId: string, breakerId: string): RelaySettings {
  return { id, name, zoneId, type, enabled: true, phases, pickupCurrentA: type === 'earth-fault' ? 50 : 500, earthFaultPickupA: type === 'earth-fault' ? 50 : undefined, timeDelayMs: 500, directional: false, tripTargetBreakerIds: [breakerId], backupTripTargetBreakerIds: [], breakerFailEnabled: true, breakerFailDelayMs: 500, state: 'idle' };
}

export function protection(id: string, type: ProtectionElement['type'], watchedObjectId: string, breakerId: string): ProtectionElement {
  return { id, type, enabled: true, watchedObjectId, phases, pickupCurrentA: type === 'earth-fault' ? 50 : 500, timeDelayMs: 500, tripTargetBreakerIds: [breakerId], state: 'idle' };
}

export function fault(id: string, targetObjectId: string, type: FaultMetadata['type'], location: Point): FaultMetadata {
  const faultPhases = type === 'A-E' ? ['A'] as Phase[] : type === 'A-B' ? ['A', 'B'] as Phase[] : phases;
  return { id, targetObjectId, type, location, phases: faultPhases, targetPhase: faultPhases.length === 1 ? faultPhases[0] : undefined, persistent: true, active: true, createdAt: new Date().toISOString(), label: type };
}

export function hotJoint(id: string, targetObjectId: string): HotJointMetadata {
  return { id, targetObjectId, phase: 'B', addedResistanceOhms: 1, thermalMassFactor: 1, ambientTemperatureC: 20, warningTemperatureC: 60, dangerTemperatureC: 90, intermittent: false, active: true, label: 'Hot joint B' };
}

function terminalsFor(type: ElectricalSymbol['type']) {
  if (type === 'source') return [{ name: 'out', x: 40, y: 0 }];
  if (type === 'load') return [{ name: 'in', x: -40, y: 0 }];
  if (type === 'earth-switch') return [{ name: 'in', x: 0, y: 0 }];
  if (type === 'transformer') return [{ id: 'hv', name: 'hv', x: -40, y: 0 }, { id: 'lv', name: 'lv', x: 40, y: 0 }];
  if (type === 'vt') return [{ name: 'tap', x: 0, y: -20 }];
  if (type === 'ct') return [{ name: 'in', x: -20, y: 0 }, { name: 'out', x: 20, y: 0 }];
  return [{ name: 'in', x: -SWITCH_TERMINAL_SPAN, y: 0 }, { name: 'out', x: SWITCH_TERMINAL_SPAN, y: 0 }];
}

function terminalId(terminal: ReturnType<typeof terminalsFor>[number], index: number): string {
  return 'id' in terminal ? terminal.id : `t-${index}`;
}
