export type Phase = 'A' | 'B' | 'C' | 'N' | 'E';

export type ViewMode = 'single-line' | 'three-phase';

export interface Point {
  x: number;
  y: number;
}

export interface Terminal {
  id: string;
  name: string;
  offset: Point;
  phaseApplicability: Phase[];
}

export interface ConnectionPoint {
  id: string;
  position: Point;
  snappedTo?: {
    objectId: string;
    terminalId?: string;
    conductorId?: string;
  };
}

export interface LabelMetadata {
  text: string;
  autoGenerated: boolean;
  manualOverride: boolean;
  marker?: string;
}

export interface SimulationMetadata {
  role?: 'source' | 'load' | 'feeder' | 'switching' | 'measurement';
  interlockGroupIds?: string[];
  damaged?: boolean;
  faulted?: boolean;
}

export interface BaseDrawingObject {
  id: string;
  type: string;
  rotation: number;
  phaseApplicability: Phase[];
  voltageLevelKv?: number;
  layerId?: string;
  viewMetadata?: Record<ViewMode, { visible: boolean }>;
  label?: LabelMetadata;
  simulation?: SimulationMetadata;
}

export interface ElectricalSymbol extends BaseDrawingObject {
  type:
    | 'source'
    | 'load'
    | 'busbar-coupler'
    | 'circuit-breaker'
    | 'disconnector'
    | 'earth-switch'
    | 'transformer'
    | 'vt'
    | 'ct'
    | 'cable-sealing-end'
    | 'line-end';
  position: Point;
  terminals: Terminal[];
  symbolVariant?: string;
}

export interface ConductorPath extends BaseDrawingObject {
  type: 'conductor-path';
  vertices: Point[];
  orthogonal: boolean;
  connectionPoints: ConnectionPoint[];
}

export interface BusbarSegment extends BaseDrawingObject {
  type: 'busbar-segment';
  vertices: Point[];
  width: number;
  connectionPoints: ConnectionPoint[];
}

export interface Label {
  id: string;
  type: 'label';
  position: Point;
  text: string;
  forObjectId?: string;
}

export interface Annotation {
  id: string;
  type: 'annotation';
  position: Point;
  text: string;
}

export interface DrawingDocument {
  id: string;
  version: 2;
  name: string;
  activeView: ViewMode;
  objects: {
    symbols: ElectricalSymbol[];
    conductors: ConductorPath[];
    busbars: BusbarSegment[];
    labels: Label[];
    annotations: Annotation[];
  };
  uiState: {
    gridSize: number;
    snapToGrid: boolean;
    snapToTerminals: boolean;
    snapToIntersections: boolean;
  };
  history?: {
    undoStack: string[];
    redoStack: string[];
  };
}
