import type { DrawingDocument, ElectricalSymbol, Phase } from '../drawing/model';

const TYPE_PREFIX: Record<ElectricalSymbol['type'], string> = {
  source: 'IN',
  load: 'LD',
  'busbar-coupler': 'BC',
  'circuit-breaker': 'CB',
  disconnector: 'DS',
  'earth-switch': 'ES',
  transformer: 'T',
  vt: 'VT',
  ct: 'CT',
  'cable-sealing-end': 'CSE',
  'line-end': 'LE'
};

const phaseMarker = (phases: Phase[]) => (phases.length < 3 || !['A', 'B', 'C'].every((p) => phases.includes(p as Phase)) ? '*' : '');

export function generateLabels(doc: DrawingDocument): DrawingDocument {
  const used = new Set<string>();
  const symbols = doc.objects.symbols.map((symbol, index) => {
    if (symbol.label?.manualOverride) {
      used.add(symbol.label.text);
      return symbol;
    }

    const base = makeBaseLabel(symbol, index + 1);
    let candidate = `${base}${phaseMarker(symbol.phaseApplicability)}`;
    let suffix = 1;
    while (used.has(candidate)) {
      suffix += 1;
      candidate = `${base}-${suffix}${phaseMarker(symbol.phaseApplicability)}`;
    }

    used.add(candidate);
    return {
      ...symbol,
      label: {
        text: candidate,
        autoGenerated: true,
        manualOverride: false,
        marker: candidate.endsWith('*') ? '* phase-specific device' : undefined
      }
    };
  });

  return { ...doc, objects: { ...doc.objects, symbols } };
}

function makeBaseLabel(symbol: ElectricalSymbol, index: number): string {
  const voltage = symbol.voltageLevelKv ? `${symbol.voltageLevelKv}kV ` : '';
  if (symbol.type === 'transformer') return `${voltage}Transformer T${index}`;
  if (symbol.type === 'source') return `${voltage}Incomer ${index}`;
  if (symbol.type === 'load') return `${voltage}Feeder ${index}`;
  return `${voltage}${TYPE_PREFIX[symbol.type]}${String(index).padStart(3, '0')}`;
}
